// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDID2C_ZvfNZdokZ6oHDJDP0y4Niw77ZbM',
    appId: '1:209858281681:web:d6b250565d14e236cb85f0',
    messagingSenderId: '209858281681',
    projectId: 'uber-fdecb',
    authDomain: 'uber-fdecb.firebaseapp.com',
    storageBucket: 'uber-fdecb.appspot.com',
    measurementId: 'G-FRDXFC83RJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6AaO-zoMGQ6v_WjoBZqVpfE24A8DyxTw',
    appId: '1:209858281681:android:bb003f00246a3aeccb85f0',
    messagingSenderId: '209858281681',
    projectId: 'uber-fdecb',
    storageBucket: 'uber-fdecb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARYlTwIgurf-OlJBtMtpw9pPRoEd_5EIQ',
    appId: '1:209858281681:ios:5a6205c71b0f8b2bcb85f0',
    messagingSenderId: '209858281681',
    projectId: 'uber-fdecb',
    storageBucket: 'uber-fdecb.appspot.com',
    iosBundleId: 'com.example.uberPractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARYlTwIgurf-OlJBtMtpw9pPRoEd_5EIQ',
    appId: '1:209858281681:ios:af4c848f22c6d95acb85f0',
    messagingSenderId: '209858281681',
    projectId: 'uber-fdecb',
    storageBucket: 'uber-fdecb.appspot.com',
    iosBundleId: 'com.example.uberPractice.RunnerTests',
  );
}
